title: My Portfolio
description: A showcase of some of my privately created analysis project dashboards, eBooks & sundry works without proprietary restrictions
logo: AOB_Tshirt.jpg
theme: jekyll-theme-minimal
