title: My Portfolio
description: A showcase of some of my privately created analysis dashboards, eBooks & sundry works without proprietary restrictionsdata analytics projects
logo: AOB_Tshirt.jpg
theme: jekyll-theme-minimal
